# Plotting Accumulated Rewards

In [34]:
import pandas as pd
import numpy as np
import glob
import re
from pandas import DataFrame

In [39]:
## First setting
list_of_files = glob.glob('./social/*3-12*.txt')   # create the list of file
dataset = DataFrame({"Step":range(400)})
count = 1;
for file_name in list_of_files:
    print(file_name)
    data = pd.read_csv(file_name,header=None)
    data = data.replace(" ", "")
    d = []
    for i in data.iloc[:,3]:
        i = re.sub(r'[ a-z]+','',i)
        d.append(i)
    dataset[str(count)] = d#.astype("float")
    #print([:5])
    count = count+1

./social/Social_3-12_eli.txt
./social/social_3-12_apoorva.txt
./social/social_3-12_xiang.txt
./social/social_3-12_cao.txt
./social/social_3-12_xianhao.txt
./social/social_3-12_lyu.txt
./social/Social_3-12_tim.txt
./social/social_3-12_snehal.txt
./social/social_3-12_lu.txt
./social/Social_3-12_marianne.txt
./social/Social_3-12_sanne.txt
./social/social_3-12_paul.txt
./social/social_3-12_han.txt
./social/social_3-12_simone.txt
./social/social_3-12_Ziyu.txt
./social/social_3-12_teresa.txt
./social/social_3-12_chitra.txt
./social/social_3-12_fanis.txt
./social/social_3-12_liu.txt
./social/social_3-12_shiyu.txt


In [40]:
print(dataset.head())

   Step    1    2    3    4    5    6    7    8    9 ...    11   12   13   14  \
0     0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0   
1     1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0   
2     2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0   
3     3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0   
4     4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0   

    15   16   17   18   19   20  
0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 21 columns]


In [44]:
reward = dataset.iloc[:,1:-1].values.astype('float')
print(reward)

[[  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 ...
 [116.  53.  56. ...  29.  33.  25.]
 [116.  53.  56. ...  29.  33.  25.]
 [116.  53.  56. ...  30.  33.  25.]]


In [46]:
avg_reward = np.mean(reward,axis=1)
print(avg_reward.shape)
print(avg_reward)

(400,)
[ 0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.52631579  0.52631579  0.52631579  0.63157895  0.63157895
  0.63157895  1.15789474  1.15789474  1.68421053  1.68421053  1.68421053
  1.68421053  1.68421053  1.73684211  1.73684211  1.73684211  2.26315789
  2.26315789  2.26315789  2.26315789  2.26315789  2.26315789  2.26315789
  2.26315789  2.26315789  2.26315789  2.78947368  2.78947368  2.78947368
  2.78947368  2.78947368  2.84210526  3.36842105  3.36842105  3.42105263
  3.42105263  3.94736842  4.          4.52631579  4.52631579  5.05263158
  5.05263158  5.57894737  5.57894737  5.57894737  5.63157895  5.68421053
  5.68421053  5.68421053  5.78947368  5.84210526  5.84210526  5.84210526
  5.84210526  6.36842105  6.42105263  6.42105263  6.42105263  6.42105263
  6.42105263  6.42105263  6.42105263  6.94736842  6.94736842  7.
  7.          7.          7.          7.          7.05263158  7.0526

## Function

In [49]:
## First setting
setting = '3-12'
def avg_reward_social(setting):
    
    list_of_files = glob.glob('./social/*'+setting+'*.txt')   # create the list of file
    dataset = DataFrame({"Step":range(400)})
    count = 1;
    for file_name in list_of_files:
        print(file_name)
        data = pd.read_csv(file_name,header=None)
        data = data.replace(" ", "")
        d = []
        for i in data.iloc[:,3]:
            i = re.sub(r'[ a-z]+','',i)
            d.append(i)
        dataset[str(count)] = d#.astype("float")
        #print([:5])
        count = count+1
    reward = dataset.iloc[:,1:-1].values.astype('float')
    avg_reward = np.mean(reward,axis=1)
    print(avg_reward.shape)
    print(avg_reward)

In [50]:
avg_reward_social(setting)

./social/Social_3-12_eli.txt
./social/social_3-12_apoorva.txt
./social/social_3-12_xiang.txt
./social/social_3-12_cao.txt
./social/social_3-12_xianhao.txt
./social/social_3-12_lyu.txt
./social/Social_3-12_tim.txt
./social/social_3-12_snehal.txt
./social/social_3-12_lu.txt
./social/Social_3-12_marianne.txt
./social/Social_3-12_sanne.txt
./social/social_3-12_paul.txt
./social/social_3-12_han.txt
./social/social_3-12_simone.txt
./social/social_3-12_Ziyu.txt
./social/social_3-12_teresa.txt
./social/social_3-12_chitra.txt
./social/social_3-12_fanis.txt
./social/social_3-12_liu.txt
./social/social_3-12_shiyu.txt
(400,)
[ 0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.52631579  0.52631579  0.52631579  0.63157895  0.63157895
  0.63157895  1.15789474  1.15789474  1.68421053  1.68421053  1.68421053
  1.68421053  1.68421053  1.73684211  1.73684211  1.73684211  2.26315789
  2.26315789  2.26315789  2.26